### ISSUE TITLE
vertaling / binding functies naar NEN 2660 niet bekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#13]
De functies in het contract (Vraagspecificatie Eisendeel) zijn ánders dan de activiteiten (Vraagspecificatie Procesdeel / ontwerp- en uitvoeringswerkzaamheden).
De functies geven weer, welke diensten het "systeem" moet vervullen tijdens het gebruik; een voorbeeld is een weg, die als functie "het verkeer moet geleiden".
de objecten in het contract zijn de functievervullers. De activiteiten zijn door mensen uit te voeren werkzaamheden tijdens het ontwerpen, bouwen, beheren en slopen van het object.

De vertaling / binding van functies en activiteiten naar NEN 2660 is nog niet bekend. 

De vertaling / binding van de relatie tussen functies en objecten naar NEN 2660 is nog niet bekend.

**Comment by RiX012** [comment]
> De functie als 'activiteit die een systeem of object uitvoert' is een erg belangrijk onderdeel van Systems Engineering en daarmee contractdocumenten in onze context. We zien de functie als een combinatie van een Activiteit en een FunctioneleEntiteit. Hiermee wordt het mogelijk om hier individuen van te maken en hier eisen (ongestructureerde voorwaarden) aan te hangen in een contact context. Samenvattend, Voorwaarden kunnen gehangen worden aan FysiekObject, Activiteit, InformatieObject en Activiteit EN FunctioneleEntiteit. Hier is geen modificatie in het NENB2660-2 model voor nodig, maar een voetnoot die dit toelicht zou handig zijn.

Dit hebben we binnen het PCB gesteld. Zou dit passen of hebben we het hier over iets anders @ElisabethKloren

**Comment by ElisabethKloren** [comment]
@RiX012 je spreekt helaas Martiaans, wat is een functionele entiteit? 
Ik wist niet dat je dit al bedacht had voor het PCB maar waarschijnlijk klopt de redenatie dan wel ;-)

**Comment by RiX012** [comment]
Martiaans? DIe begrijp ik dan weer niet :)
https://bimloket.github.io/nen2660/term#FunctionalEntity

**Comment by ElisabethKloren** [comment]
@RiX012 begrijp ik het zo goed
"An entity involving the external behavior (function) of the object where the output contributes to stakeholder objectives (what it does) implemented/played by technical entities"@en" 

Dus dat is een soort, ehh, functioneel object (spreektalig zeg maar) die dan weer een activiteit uitvoert, dus moet je zeggen dat er een kolom bijkomt in de onderwerpentabel die aangeeft welke FunctionalEntity de activiteit uitvoert, en daar kan de gebruiker dan uit afleiden dat de "functie" bedoeld wordt in systems engineering. En dan moeten de functional entity's ook worden opgenomen in de onderwerpentabel? En activiteiten die door het bouwbedrijf / een mens worden uitgevoerd zijn activiteiten die geen bijbehorende FunctionalEntity  hebben?

"Opstellen maanrapportage" = Activiteit
"Afwikkelen wegverkeer" = Activiteit uitgevoerd door functionele entiteit "Provinciale weg N224"

**Comment by ElisabethKloren** [comment]
Martiaans = NEN2660-iaans

**Comment by RiX012** [comment]
@ElisabethKloren dit is een van de lastigste. Ik weet niet of ik hier helemaal goed antwoord op kan geven. Maar het komt er op neer dat "Opstellen maandrapportage" een `Activity`  is en dat "Afwikkelen wegverkeer" zowel een `Activity` EN een `FunctionalEntity` is.

**Comment by RiX012** [comment]
Verwekt in model, nog niet in spec

**Comment by ElisabethKloren** [comment]
verwerkt in de tekst, hoop ik
