### ISSUE TITLE
vertaling / binding "doelen" project naar NEN 2660 niet bekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#14]
Bij het functioneel specificeren begin je met het vaststellen van de doelstellingen van het systeem. Vanuit die doelstellingen bedenk je welke functies het systeem nodig heeft.

De vertaling / binding van doelen naar NEN 2660 is nog niet bekend. 

De vertaling / binding van de relatie tussen doelen en functies naar NEN 2660 is nog niet bekend.

**Comment by RiX012** [comment]
Overlap met #30 

Dat ligt er uiteraard aan welke geloof je hebt. Ik zou zeggen, dat een standaard die dit specificeert en committeer je er aan.
Als duidelijk is wat een 'Doel' is kun je de juiste binding in de NEN2660-2 kiezen. Bijvoorbeeld 'Toestand' zou kunnen (specialisatie: GewensteToestand)

**Comment by ElisabethKloren** [comment]
Wegens overlap met Overlap met Issue #30 sluit ik deze; ik denk dat de gebruikers inderdaad eerst het verschil zullen moeten tonen tussen eis en doel; vooralsnog houdt ik wel vast aan een doelentabel, om te zien of hier in de openbare aanbesteding behoefte aan is.
