### ISSUE TITLE
Vertaling / Binding verificatiemethode en -moment naar NEN 2660 is nog niet bekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#15]
## Verificatiemethoden
Gebruikelijk is in contracten het aangeven van een of meer verificatiemethodes, eventueel met een of meer verificatiemomenten. 

De vertaling / binding van een verificatiemethode- en moment naar NEN 2660 is nog niet bekend.

**Comment by RiX012** [comment]
Dat is nu deze:
https://bimloket.github.io/nen2660/def#verificationMethodType
