### ISSUE TITLE
Eigenaar van object, Vertaling / Binding naar NEN 2660 niet bekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#16]
Vooral bij objecten is het voor de opdrachtgever handig, te weten wie de eigenaar is. De eigenaar is de persoon of rol bij de opdrachtgever die verantwoordelijk is voor beheer van dit objecttype, en die geconsulteerd moet worden bij afwijking van de eisen.

De Vertaling / Binding van eigenaar naar NEN 2660 is nog niet bekend.

**Comment by RiX012** [comment]
NEN2660-2 zegt niets over persons of Agents. Wellicht DC Terms voor aanspreken. Bijvoorbeeld:
http://purl.org/dc/terms/rightsHolder

**Comment by ElisabethKloren** [comment]
Ok, dan gaan we daar voorlopig van uit voor de openbare consultatie, waar ook de commissieleden van de NEN-2660 voor zullen worden uitgenodigd.
