### ISSUE TITLE
Vertaling / Binding van Toelichting op eistekst naar NEN 2660 onbekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#17]
Een contractuele eis kan onderbouwd worden met een toelichting.

De Vertaling / Binding van toelichting naar NEN 2660 is nog niet bekend.

**Comment by RiX012** [comment]
Dit is de taalbinding voor Annotaties. Een toelichting zou je kunnen toevoegen met eventueel skos:note

![afbeelding](https://user-images.githubusercontent.com/56293445/143460361-fad5d261-376e-437d-998e-9a4a0e7e641f.png)

**Comment by ElisabethKloren** [comment]
Prima toch, dan maak ik er 

https://www.w3.org/2009/08/skos-reference/skos.html#note 

van, met link
