### ISSUE TITLE
Vertaling / binding van relatie tussen eisen en documenten is onbekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#19]
4.2.7 Bron
De bron van de eis kan naart twee zaken verwijzen:

De URI van de gebruikte eis uit een bibliotheek (indien deze niet gewijzigd is). Deze URI verwijst naar een openbaar gepubliceerde eis in een bibliotheek, bijvoorbeeld het Provinciaal Contracten Buffet. De interpretatie is hierbij dat de eis in het project een nadere detaillering (verbijzondering) is van de eis uit de bibliotheek, en dus ook een andere URI heeft. De velden die in de bibliotheek zijn ingevuld (bijvoorbeeld titel en tekst van de eis) mogen in dat geval niet worden gewijzigd. Aanvullingen met nieuwe velden en relaties mogen wel worden gedaan.
De URI van een brondocument met herkomst van de eis. Deze uri verwijst naar een document in de documententabel.
issue 23

4.2.8 Referentiedocument
Als in de eistekst wordt verwezen naar een referentiedocument, staat in deze kolom de URI van het gerefereerde document. Deze uri verwijst naar een document in de documententabel.

4.2.9 Locatie in document
Als zowel een pdf (voor mensen leesbare versie) als een dataset met eisen worden meegenomen, dan staat in deze kolom de URI die verwijst naar een paragraaf in een document in de documententabel.

Wat is de vertaling/binding van de relatie tussen de eis en deze documenten is onbekend

**Comment by RiX012** [comment]
Heeft deze geen overlap met #23?

Relatie van eis naar bibliotheek eis zou ik als kopie zien (eventueel met `rdfs:seeAlso`.

Relatie naar brondocument is inderdaad een URI. De locatie zou een property van de property kunnen zijn. `rdfs:comment` bijvoorbeeld... Ik vind moeilijk om dit verder te formaliseren.

**Comment by ElisabethKloren** [comment]
@RiX012 begrijp ik goed dat je advies is om rdfs:comment te gebruiken, en het niet verder te formaliseren? Of vindt je dit al te ver gaan?

**Comment by RiX012** [comment]
> @RiX012 begrijp ik goed dat je advies is om rdfs:comment te gebruiken, en het niet verder te formaliseren? Of vindt je dit al te ver gaan?

Ik vind het lastig in te schatten wat het gebruik is. Maar als het inderdaad gaat om meer een 'ter info' met niet zo'n sterke semantiek zou je inderdaad daar kunnen beginnen

**Comment by ElisabethKloren** [comment]
Bij "reden vervallen status" heb je skos:note gekozen, hier dus rdfs:comment?

**Comment by RiX012** [comment]
`skos:note`  is echt voor toelichtingen. Hier hebben we het echt over iets wat we eigenlijk niet precies de semantiek van weten. Dan is `rdfs:comment`  het meest niets zeggende. Niet mooi dus... Maar kan voor nu genoeg zijn
