### ISSUE TITLE
Vertaling / binding van initiator van eis naar NEN 2660 onbekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#21]
### Initiator
Initiator van de eis (naam natuurlijk persoon en/of organisatie).

De vertaling / binding van initiator naar NEN 2660 is nog niet bekend.

**Comment by RiX012** [comment]
Hier zegt de NEN2660-2 niets over. 

Hiervoor zou je DC Terms kunnen gebruiken, wellicht:
`http://purl.org/dc/terms/publisher`

**Comment by ElisabethKloren** [comment]
Van de PCB gebruikers hoor ik dat het ze meer om de "eigenaar" gaat, ik heb het nu net zo geïnterpreteerd als bij het object: [dcmi-terms:rightsHolder](https://dublincore.org/specifications/dublin-core/dcmi-terms/#rightsHolder)
