### ISSUE TITLE
De vertaling / binding van status en reden vervallen van eis naar NEN 2660 is nog niet bekend. 

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#22]
### Status
Gebruikers willen de status toevoegen aan de eis, zoals "actueel" of vervallen"

De vertaling / binding van status naar NEN 2660 is nog niet bekend. 

### Reden vervallen
Gebruikers willen de reden van vervallen toevoegen aan de eis, zodat de status onderbouwd is.

De vertaling / binding van de reden van vervallen naar NEN 2660 is nog niet bekend.

**Comment by RiX012** [comment]
De NEN2660-2 stelt dit voor:
![afbeelding](https://user-images.githubusercontent.com/56293445/143458229-5d1a9b15-5355-4bd8-bdaa-aecff5a7c2ad.png)

**Comment by ElisabethKloren** [comment]
@RiX012 Dus status = heeftToestand, heb jij daar zo'n mooi linkje voor (wat is toestand in het engels?) 

En dan bij toelichting op de statatus: skos:comment?

**Comment by RiX012** [comment]
https://bimloket.github.io/nen2660/term#State

Comments kunnen inderdaad altijd.

**Comment by RiX012** [comment]
Verwekt in model, nog niet in spec
Het is toch een property geworden `status` op de `requirement` met een enumeratielijst.
de toelichting is ook een property geworden `statusToelichting`

**Comment by RiX012** [comment]
#43 fixed dit
