### ISSUE TITLE
URI bibliotheek-eis versus in project gebruikte eis

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#23]
### URI
In deze kolom staat de unieke naam (URI) van de eis. Zie [URI conform W3C](https://www.w3.org/wiki/URI). 

De URI is unieke naam voor de eis binnen het project. 
Bij de eisen kan verwezen worden naar een eis in een eisenbibliotheek onder "Bron". **waarom?**

Bij de eisen kan de URI ook de verwijzing zijn naar de eis in een bibliotheek; dan mogen de overige kolommen niet zijn aangepast en er ook geen extra informatie zijn toegevoegd. 

Vraag: is het nodig om de eis uit de bibliotheek een project-specifieke URI te geven, waarom en welke regels zijn er als je wel de URI van de eis uit de bibliotheek (bijvoorbeeld het Provinciaal Contracten Buffet) gebruikt?

**Comment by ElisabethKloren** [comment]
Vraag is herschreven na gesprek met PCB leden:
De bron van de eis kan naart twee zaken verwijzen: 
1. De URI van de gebruikte eis uit een bibliotheek (indien deze niet gewijzigd is). Deze URI verwijst naar een openbaar gepubliceerde eis in een bibliotheek, bijvoorbeeld het Provinciaal Contracten Buffet. De interpretatie is hierbij dat de eis in het project een nadere detaillering (verbijzondering) is van de eis uit de bibliotheek, en dus ook een andere URI heeft. De velden die in de bibliotheek zijn ingevuld (bijvoorbeeld titel en tekst van de eis) mogen in dat geval niet worden gewijzigd. Aanvullingen met nieuwe velden en relaties mogen wel worden gedaan.
2. De URI van een brondocument met herkomst van de eis. Deze uri verwijst naar een document in de documententabel.

De enige vraag die nu openstaat is: moeten deze twee bronnen in aprte kolommen staan > en wat is de vertaling/binding naar NEN 2660?

**Comment by RiX012** [comment]
> De URI is unieke naam voor de eis binnen het project.

Meestal is een URI überhaupt uniek.

**Comment by ElisabethKloren** [comment]
Ja, hier wordt bedoelt dat als het project een eis uit een bibliotheek gebruikt en daar zaken aan toevoegt, dat de eis dan een unieke id moet krijgen binnen het project; maar als de bibliotheek-eis ongewijzigd gebruikt wordt niet.

O nee, dat is onmogelijk, want je koppelt de eis vast aan een project-onderwerp... 

Misschien moet ik hier schrijven: een eis uit een bibliotheek kan gebruikt worden als bron voor een eis in het project. De project-eis die is afgeleid van de eis in een bibliotheek krijgt een eigen, nieuwe URI voor het project.

Dan blijft de vraag voor @RiX012: welke NEN2660-relatie hebben de project-eis en de bibliotheek-eis? Of standaard skos relatie?

**Comment by RiX012** [comment]
> Vraag is herschreven na gesprek met PCB leden: De bron van de eis kan naart twee zaken verwijzen:
> 
>     1. De URI van de gebruikte eis uit een bibliotheek (indien deze niet gewijzigd is). Deze URI verwijst naar een openbaar gepubliceerde eis in een bibliotheek, bijvoorbeeld het Provinciaal Contracten Buffet. De interpretatie is hierbij dat de eis in het project een nadere detaillering (verbijzondering) is van de eis uit de bibliotheek, en dus ook een andere URI heeft. De velden die in de bibliotheek zijn ingevuld (bijvoorbeeld titel en tekst van de eis) mogen in dat geval niet worden gewijzigd. Aanvullingen met nieuwe velden en relaties mogen wel worden gedaan.
> 
>     2. De URI van een brondocument met herkomst van de eis. Deze uri verwijst naar een document in de documententabel.
> 
> 
> De enige vraag die nu openstaat is: moeten deze twee bronnen in aprte kolommen staan > en wat is de vertaling/binding naar NEN 2660?

Punt 2 is helemaal correct en is gewoon een URI zonder dat hier de NEN2660-2 bij betrokken hoeft te worden.
Punt 1 is denk ik niet correct. De bibliotheek eis is contextloos en wat mij betreft is de relatie tussen de bibliotheekeis en de projecteis 'impliciet'. Het is eigenlijk een kopie van, die niet persé meer een relatie met de bibliotheek heeft. Mocht je alsnog een relatie willen leggen dan is waarschijnlijk een `rdfs:seeAlso` voldoende voor nu

**Comment by ElisabethKloren** [comment]
De relatie is dus in beide gevallen hetzelfde, namelijk  `rdfs:seeAlso`  en er zijn geen twee kolommen nodig.
