### ISSUE TITLE
Vertaling / binding van eistype / type verificatiemethode naar NEN 2660 niet bekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#24]
In deze kolom staat het eistype.
Bij eisen: voorstel om toe te passen de lijst uit de [Leidraad Systems Engineering versie 3](https://www.leidraadse.nl/assets/files/downloads/LeidraadSE/V3/Leidraad_V3_SE_web.pdf):

* <a>Topeis</a> (systeemeis?)
* <a>Proceseis</a>
* <a>Functieeis</a>
* <a>Aspecteis</a>
* <a>Betrouwbaarheid</a>
* <a>Beschikbaarheid</a>
* <a>Onderhoudbaarheid</a>
* <a>Veiligheid</a>
* <a>Gezondheid</a>
* <a>Omgeving</a>
* <a>Duurzaamheid</a>
* <a>Vormgeving</a>
* <a>Toekomstvastheid</a>
* <a>Sloopbaarheid</a>

Bij verificatiemethoden: voorstel om toe te passen de lijst uit NEN-EN-ISO 9000:2015 Kwaliteitsmanagementsystemen - Grondbeginselen en verklarende woordenlijst
* <a>Vaststellen</a>
* <a>Beoordelen</a>
* <a>Monitoren</a>
* <a>Meten</a>
* <a>Keuren</a>
* <a>Beproeven</a>
* <a>Evalueren</a>

Vraag: wat is de vertaling / binding van deze kolom in de eistabel naar NEN 2660?

**Comment by ElisabethKloren** [comment]
Vraag aan @RiX012: wat is de vertaling / binding van deze kolom in de eistabel naar NEN 2660? De lijst met verificatiemethoden wordt nog aangevuld door @thomasmunster

**Comment by RiX012** [comment]
Binnen de NEN2660-2 erkennen ze dezelfde problematiek die @thomasmunster  onderschrijft. Vandaar dat er voor gekozen is om te zeggen dat er zoiets bestaat als een Verificatiemethode, dat dat een lijst is maar dat iedereen vrij is om de waarden binnen die lijst zelf te specificeren.

**Comment by ElisabethKloren** [comment]
@RiX012 ik lees wat je hebt toegevoegd in de tekst maar begrijp het nog niet helemaal:
"Een verificatiemethode is geen activiteit. Het gaat hier om extra informatie bij een eis. Een verificatiemethode is een eigenschap van een eis in de NEN2660-2. De eigenschap heeft een enumeratie van de verschillende mogelijke methoden. 

Een verificatiemethode heeft een vertaling in de NEN2660-2 als 'property' van een eis."


Optie 1: de property verificatiemethode zijn er stiekum twee in het dagelijks gebruik:  (1)  een vrij tekst veld, en (2) het type verificatiemethode uit een lijst. Wat is daarvan de vertaling/binding? 
Optie 2: Of is elke verificatiemethode wel ook een  "informatieobject" met alles erop en eraan, en moet je in de eistabel alleen verwijzen naar de URI van de verificatiemethode?

**Comment by RiX012** [comment]
@ElisabethKloren In de consultatieversie van de NEN2660-2 was een verificatiemethode een eis (aan een eis). Dus een eigen informatieobject. Omdat nu (mede door input van Bob en mij) geconstateerd is dat de verificatiemethode eigenlijk meer een informatieveld van de eis is ("zo moet je hem verifieren") is het dus als property van de eis gemodelleerd. En in dit geval een property die een waardelijst heeft, waarvan de waardes per dataset ingevuld kunnen worden. Optie 1 dus, maar zonder het vrije tekst veld stuk.

**Comment by ElisabethKloren** [comment]
@RiX012 o-oo kan het vrije tekst veld dan een 'rdfs:comment' zijn? of zo iets?

**Comment by RiX012** [comment]
Ja, maar dat is dan als toelichting. Niet een nieuwe verificatiemethode ofzo

**Comment by ElisabethKloren** [comment]
ok, dan neem ik het zo op
