### ISSUE TITLE
Informatiemodel voor documenten onbekend

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#25]
Voorstel is om de onderstaande tabel te gebruiken voor de volgende soorten documenten:

Brondocumenten voor eisen
Van toepassing zijnde documenten, waarnaar verwezen wordt in een eistekst.
Overige contractuele documenten, zodat ook teksten in paragraven kunnen worden toegevoegd als data.
De vertaling / binding van documenten naar NEN 2660 is NEN2660:InformatieProduct. Merk op: ook een eis wordt gezien als InformatieProduct; maar deze wordt opgenomen in de Eisentabel. In de onderwerpentabel zijn te leveren documenten/datasets (informatieleveringen) óók Informatieproduct. De informatieleveringen die gevráágd worden in het contract, staan niet in de Documententabel.

In de tabel staat op de tweede regel een korte toelichting op de inhoud; op de derde regel de vertaling / binding naar NEN 2660 (of andere standaard?)

Welk informatiemodel te gebruiken voor de documententabel?

**Comment by ElisabethKloren** [comment]
@RiX012 zijn de velden in de documententabel al te vinden in een (inter)nationale standaard die we zouden kunnen gebruiken?

**Comment by ElisabethKloren** [comment]
PS als paragraaf en hoofdstuknummering niet handig zijn maar beter gewerkt kan worden met één volgnummer en een  "heeft deel" relatie is dat ook geen probleem. Wat maar het meest generiek toepasbaar is.

**Comment by RiX012** [comment]
In het kader van PCB heb ik dit voorgesteld. Dat zou kunnen werken:
![afbeelding](https://user-images.githubusercontent.com/56293445/143454111-82be40ca-3e45-430e-b77b-3b8d34f2ab46.png)

**Comment by ElisabethKloren** [comment]
Zie ook deze issue: https://github.com/Stichting-CROW/Contracteisen/issues/16


Je zou eigenlijk niet willen praten in termen van hoofdstuk en paragraaf, maar in iets algemeners, zoals hasPart > dan kan je zelf het aantal lagen bepalen.

**Comment by RiX012** [comment]
Ik weet niet of ik het helemaal goed begrijp, maar InformatieObject (wat een Document, Hoofdstuk en Paragraaf allemaal kan zijn) kan sowieso al een hasPart hebben. Dus wat dat betreft past het al.

**Comment by ElisabethKloren** [comment]
@RiX012 Maar waarom onderscheid maken tussen een hoofdstuk en een paragraaf?

**Comment by RiX012** [comment]
Dat hoeft niet, maar het kan :)

**Comment by ElisabethKloren** [comment]
Ja, maar beter van niet met deze reden: in de RAW is sprake van een hoofdstuk, een deelhoofdstuk en dan een paragraaf. Beter houden we het generiek op een Tekstdeel oid

**Comment by RiX012** [comment]
Deze moeten we even in detail uitwerken met de Blueprint Manager ernaast

**Comment by ElisabethKloren** [comment]
ik zie dat je deze hebt uitgewerkt, ik sluit de issue:

<html>
<body>
<section id="documentsectie" style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="header-wrapper" style="display: flex; align-items: baseline;"><br class="Apple-interchange-newline"><a class="self-link" href="https://bimloket.github.io/contractspecificaties/#documentsectie" aria-label="Permalink for Section 5.2.8" style="color: inherit; text-decoration: none; border-bottom: 1px solid rgb(112, 112, 112); padding: 0px 1px; margin: 0px -1px; order: -1; position: relative; left: -1.1em; font-size: 1rem; opacity: 0.5;"></a></div><p style="margin: 1em 0px;">In deze kolom staat de documentsectie. Deze kan gebruikt worden om een document verder op te delen. Middels de 'heeft deel' relatie kunnen net zoveel secties aan een document toegevoegd worden als er nodig zijn.</p>

Taalbinding | Kardinaliteit | Datatype
-- | -- | --
nen2660:hasPart | 0:n (t.o.v. Document) | xsd:anyURI

</section>
</body>
</html>In deze kolom staat de documentsectie. Deze kan gebruikt worden om een document verder op te delen. Middels de 'heeft deel' relatie kunnen net zoveel secties aan een document toegevoegd worden als er nodig zijn.

Taalbinding	Kardinaliteit	Datatype
[nen2660:hasPart](https://bimloket.github.io/nen2660/term#hasPart)	0:n (t.o.v. Document)	[xsd:anyURI](https://www.w3.org/2001/XMLSchema#anyURI)
5.2.9 DocumentSectieNaam
De DocumentSectieNaam is de voor mensen leesbare naam van het onderwerp. Deze naam hoeft niet uniek te zijn in het project, maar dat is natuurlijk wel handig.

Taalbinding	Kardinaliteit	Datatype
[skos:prefLabel](https://www.w3.org/2009/08/skos-reference/skos.html#prefLabel)	1:1 (t.o.v. DocumentSectie)	[xsd:string](https://www.w3.org/2001/XMLSchema#string)
5.2.10 DocumentSectieTekst
In deze kolom staat de paragraaftekst.

Taalbinding	Kardinaliteit	Datatype
[rdf:value](http://www.w3.org/1999/02/22-rdf-syntax-ns#value)	0:1 (t.o.v. DocumentSectie)	[xsd:string](https://www.w3.org/2001/XMLSchema#string)
