### ISSUE TITLE
Gebruikerswens 4.2.10 Systeemeis ipv Topeis

### ISSUE THREAD

**Issue by BobNonnekens** [bimloket/contractspecificaties#27]
1.	Als SE'er levert de term Topeis verwarring op omdat dit met name een urgentie specificeert (de belangrijkste eis van een reeks). Beter gebruiken we de aanduiding Systeemeis om daarmee het beoogde abstractie-/decompositieniveau aan te duiden zodat de verwarring verdwijnt.
2.	Bob Nonnekens, opsteller attributentabel CROW
3.	27-9-2021
4.	Must have - Verbetervoorstel
5.	Zsm wijzigen om redenen beschreven bij 1

**Comment by ElisabethKloren** [comment]
Voorstel van PCB werkgroep: gebruik de volgende typen eisen:

Functie-eis, Systeemeis, Proceseis, Informatie-eis, Aspect-eis

Van de aspecteisen de types die al genoemd worden in de documentatie.
