### ISSUE TITLE
Is een doel niet hetzelfde als een eis?

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#30]

**Comment by RiX012** [comment]
Dat ligt er uiteraard aan welke geloof je hebt. Ik zou zeggen, dat een standaard die dit specificeert en committeer je er aan.

**Comment by ElisabethKloren** [comment]
ik denk dat de gebruikers inderdaad eerst het verschil zullen moeten tonen tussen eis en doel; vooralsnog houdt ik wel vast aan een doelentabel, om te zien of hier in de openbare consultatie behoefte aan is. 

Aanname: een projectdoel is een heel belangrijke eis,
