### ISSUE TITLE
Verbetervoorstel: interne verwijzingen ook human-readable maken

### ISSUE THREAD

**Issue by rrense** [bimloket/contractspecificaties#31]
_Geen idee of het de bedoeling is dat iedereen issues kan aanmaken, maar wilde graag mijn feedback leveren op dit interessante initiatief._

De interne verwijzingen in de tabellen gaan nu middels de URI's. Bijv. in de eistabel wordt de `specificeert` ingevuld met de URI van het onderwerp. Is het niet wenselijker om hier ook een human-readable verwijzing aan toe te voegen?

Voordelen:
- Er kan eenvoudig een menselijke controle plaatsvinden. Zonder dat hiervoor bijv. in Excel met lookup-formules gewerkt hoeft te werken.
- Daarmee wordt het ook mogelijk een daadwerkelijke uitgangscontrole uit te voeren als aanbestedende partij, zonder te moeten vertrouwen op de technische implementatie, wat voor veel eindgebruikers een black-box is.
- Dit gaat ook helpen met #11 

Nadelen:
- Informatie wordt dubbel uitgeleverd. Er is een risico dat deze afwijken van elkaar. (hoewel een deugdelijke implementatie dat zou moeten voorkomen)
- Het "speciale" karakter van de data-set vermindert. Hierdoor kunnen eindgebruikers in de verleiding komen om last-minute aanpassen in de csv te doen, met kwaliteitsverlies tot gevolg.

Wat achtergrond: In het verleden heb ik veel te maken gehad met coins-containers. Doordat een gemiddelde eindgebruiker die niet eenvoudig "even" kan bekijken, kon die geen uitgangscontrole doen. Daardoor werden overduidelijke problemen in zijn geheel niet gespot en kon het voorkomen dat er helemaal geen data in zat, of bepaalde data miste (terwijl die wel in het bronsysteem van de eindgebruiker aanwezig was)

**Comment by ElisabethKloren** [comment]
Hoi @rrense wat super dat je dit doet, we gaan dit document binnenkort in een openbare consultatie gooien dus je bent nu gewoon de koploper van de koplopers! Feedback is zeker welkom!

**Comment by ElisabethKloren** [comment]
Besluit: weliswaar kunnen dubbelingen voorkomen, en bestaat het gevaar dat deze lijsten handmatig worden aangepast waarbij mensen fouten maken, toch is het argument van leesbaarheid voor mensen zwaarwegender, juist omdat dit een instapmodel moet zijn om de sector in beweging te krijgen. we maken de tabellen meer human-readable.
