### ISSUE TITLE
Bug: kardinaliteiten in documententabel

### ISSUE THREAD

**Issue by rrense** [bimloket/contractspecificaties#32]
In de documententabel hebben `Hoofdstuknummer`, `Hoofdstuktitel`, `Paragraafnummer`, `Paragraaftitel` en `Paragraaf tekst` nu een kardinaliteit van `1:1`. 
Als een document een brondocument is, is dit echter al vastgelegd als `Locatie in document` in de eisentabel. 
Een kardinaliteit van `0:1` lijkt dan logischer.

**Comment by ElisabethKloren** [comment]
Commentaar verwerkt, bedankt voor deze scherpte
