### ISSUE TITLE
Aanleveren dereferencable link naar NEN 2660 voor "eistype"

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#36]
Aanleveren dereferencable link naar NEN 2660 voor "eistype"

**Comment by RiX012** [comment]
de property (relatie) is: https://w3id.org/nen2660/def#requirementTopicType
het enumeratype is deze: https://w3id.org/nen2660/def#RequirementTopicType
Van die laatste moeten alle zaken onder https://bimloket.github.io/contractspecificaties/#enum-eistype dus instanties worden.

**Comment by RiX012** [comment]
Verwekt in model, nog niet in spec

**Comment by ElisabethKloren** [comment]
verwerkt in tkest
