### ISSUE TITLE
Relatie fase - verificatiemethode

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#39]
Relatie fase - verificatiemethode: ja, hier is de NEN 2660 dus een beetje onhandig voor ;-)

**Comment by RiX012** [comment]
Na uitgebreid overleg met de NEN2660-2 commissie is besloten dat het model van NEN2660-2 te restrictief was op dit gebied. Daarom is besloten om de relatie Eis > heeftVerificatieMethode > VerificatieMethode er uit te halen. Dit is jammer vanwege de standaardisatie, maar goed omdat we meer mogelijkheden hebben. Het betekent tevens dat we nu _toch_ een eigen stukje ontologie moeten maken onder de NEn2660-2 (naast de EnumeratieTypen) dit is helaas niet anders. 

Mijn voorstel is om zoiets te maken:

![afbeelding](https://user-images.githubusercontent.com/56293445/163951088-235a3dc0-11ec-4aab-92fb-b2231eb98e44.png)

**Comment by RiX012** [comment]
Besluit: Inderdaad eigen stukje ontologie ontwikkelen op bovenstaande manier. Waarbij de multipliciteiten altijd 0:* is. 
@RiX012 werkt stukje ontologie uit.

**Comment by RiX012** [comment]
Gedaan in BPL "Contractspecificaties Ontologie"

**Comment by RiX012** [comment]
Verwekt in model, nog niet in spec

**Comment by ElisabethKloren** [comment]
verwerkt in de spec
