### ISSUE TITLE
Eisen aan tekst in cellen

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#42]
Moeten we eigenlijk nog regels opstellen voor de "tekst" die in een cel van het format kaan staan? Aantal tekens, beperking van mogelijke leestekens, ???. Gezien de inleesbaarheid in systemen.

**Comment by Kees-JensvdWel** [comment]
Ik zou hier wel regels voor opnemen, met name het aantal tekens. Bij procesmatige eisen zijn Opdrachtgevers nu nog gewend om complete alinea's op te nemen in eisteksten. Dit moeten we voorkomen.

**Comment by ElisabethKloren** [comment]
Zie #45
