### ISSUE TITLE
Official Release: Publicatie contractspecificatie-model op data.crow.nl 

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#49]
De links naar data.crow.nl, de uitbreiding van het informatiemodel, werken niet in het document > voorbeeld bij de eistypen: https://data.crow.nl/contractspecificaties/id/Informatie-eis

MB vraagt in #44 : Links naar div. informatie-items in dit document zijn (nog) niet resolvable, zoals https://data.crow.nl/contractspecificaties/def/hasAsSubject. Los dit of, of verwijder de links.

**Comment by RiX012** [comment]
Deze kunnen pas resolvable worden als het model gereed is. Want dan wordt de ontologie geplaatst op het SPARQL-endpoint. In de tussentijd zijn dit dus wel de ID's. Mijn voorstel is om dit even te laten staan.

**Comment by ElisabethKloren** [comment]
akkoord, dan laat ik deze issue nog even open staan

**Comment by RiX012** [comment]
Middels een redirect is dit nu gedaan. Alles mbt contractspecificaties (dus niet nen2660) wordt nu geredirect naar de ld-viewer van BIM Loket. Zie voorbeeld: https://data.crow.nl/contractspecificaties/def/PhysicalObject
