### ISSUE TITLE
Verificatieplan wordt Verificatievoorschrift

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#52]
MB zegt: Voeg een vierde tabel toe voor verificatieplannen. Er wordt nu gesuggereerd dat er slechts 1 verificatieplan is per project. Dit lijkt me niet redelijk: ga ervan uit dat er meerdere plannen zijn die samen de complete scope afdekken.

Omdat verificatieplan in de sector ook in gebruik is als "document waarin je voor een specifieke fase van het project plant welke verificaties zullen plaatsvinden" wordt de term gewijzigd in EisverificatieplanURI, EisverificatieplanMethode, EisverificatieplanFase, EisverificatieplanToelichting
Waarmee hopelijk duidelijker wordt dat het een verificatieplan voor de eis betreft

@RiX012 wijzig jij dit ook in het model? Of is dit niet nodig?

**Comment by RiX012** [comment]
Dus wil je overal waar Verificatieplan staat nu "Eis" voorzetten?

**Comment by ElisabethKloren** [comment]
Ja, helaas wel ;-)

**Comment by RiX012** [comment]
De titels van de kolommen corresponderen niet met hetgeen in het model (opzettelijk) dus dat maakt niet zoveel uit. Wat ik wel zal doen is de model items `VerificationPlan`  en `verificationMethod` hernoemen naar `RequirementVerificationPlan` en `requirementVerificationMethod`. De properties (zoals `fase`, `toelichting`) worden 1 keer gedefinieerd en verlenen aan het gebruik in context hun semantiek, dus die pas ik niet aan (is dus al ok).

**Comment by ElisabethKloren** [comment]
Al right

**Comment by ElisabethKloren** [comment]
sluit ik deze nu onterecht, omdat je dit misschien nog niet verwerkt hebt?

**Comment by ElisabethKloren** [comment]
Nog meer review gehad, we lijken nu op de term Verificatievoorschrift uit te komen, dat is de gebruikelijke spreektaal

**Comment by RiX012** [comment]
@ElisabethKloren pas je deze nu zelf aan in de BPL of zal ik dat blijven doen?

**Comment by ElisabethKloren** [comment]
@RiX012 ik ga dit doen, goede oefening voor me
