### ISSUE TITLE
Turtle van concept-informatiemodel

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#59]
[rrbk](https://hypothes.is/u/acct%3Arrbk%40hypothes.is)
[31 okt.](https://hypothes.is/a/TOuE6lkuEe29VnMxB9C6Sg)
[Public](https://hypothes.is/groups/__world__/public)
1.4 Informatiemodel
Model - Ik lijk nergens het volledige Contractspecificaties- model (in UML en RDF) terug te kunnen zien. Ook niet de samenhang met de NEN2660. Waarom niet? Zo kan ik bijv. niet/lastig achterhalen wat het supertype is van Verificatieplan.

Hide replies (1)

[Elisabeth.de.Vries](https://hypothes.is/u/acct%3AElisabeth.de.Vries%40hypothes.is)
[Just now](https://hypothes.is/a/2W111l9pEe2kzmuhpjJX_g)
Ja, snap ik voor een techneut als jij > het model wordt gepubliceerd op crow.data.nl als de gebruikerswensen qua tabellen stabiel zijn, ik kan Rik vragen of er al een turtle van het concept te publiceren valt op Github

**Comment by RiX012** [comment]
Dat kan, doen na verwerking van review?

**Comment by ElisabethKloren** [comment]
ja, dat lijkt me prima

**Comment by RiX012** [comment]
Mapje maken met `code` , de metadata.json en de .ttl file in. Vermelding maken in 1.5.2

**Comment by RiX012** [comment]
Gedownload van Endpoint en geplaatst op https://github.com/bimloket/contractspecificaties/blob/master/data/Contractspecificaties-Ontology.ttl

Ook vermelding in de handleiding gemaakt.
