### ISSUE TITLE
Viewer van (concept)informatiemodel

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#60]
Hoi @RiX012 hoeveel moeite kost het om een viewer in te richten van het informatiemodel van contractspecificaties? Is dit haalbaar voor de release 2022?

**Comment by RiX012** [comment]
Ja, wanneer het ok is om dit in een CROW onto-verkenner instantie te doen is het prima haalbaar

**Comment by RiX012** [comment]
Initiële release op: https://docs.crow.nl/onto-verkenner/contractspecificaties/

**Comment by RiX012** [comment]
Definitieve release op https://bimloket.github.io/ld-viewer/contractspecificaties
