### ISSUE TITLE
Rol van eis in verificatieplan

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#61]
[rrbk](https://hypothes.is/u/acct%3Arrbk%40hypothes.is)
[31 okt.](https://hypothes.is/a/vh72sFkuEe224_N5S-O_yQ)
[Public](https://hypothes.is/groups/__world__/public)
3.2.7 VerificatieplanURI
Verificatieplan - In het huidige verificatieplan-model wordt een eis geverifieerd door een verificatieplan. Echter, middels een verificatieplan wordt een eis geverifieerd in relatie tot een subject. Oftewel, de rol die een eis speelt in relatie tot een onderwerp wordt geverifieerd. Waarom is deze ''rol'' en het ''verificatieplan'' samengenomen in één element (Verificatieplan)?

@RiX012 kun jij dit uitleggen?

https://bimloket.github.io/contractspecificaties/v/contractspecificaties@CR-20220815/#eisheeftonderwerp

**Comment by RiX012** [comment]
Nee ik snap de vraag niet. Van wie komt deze?

**Comment by RiX012** [comment]
> Nee ik snap de vraag niet. Van wie komt deze?

rrbk: 
Het komt erop neer, dat ik me afvroeg of ook is overwogen om de rol van de eis (de ‘’specifier’’) expliciet te maken en daarop het verificatieplan vast te leggen?  Zie hieronder.
Ik was benieuwd (ter lering en vermaak) welke alternatieven er waren en hoe het huidige voorstel tot stand is gekomen?
![afbeelding](https://user-images.githubusercontent.com/56293445/203529421-f6938d77-f755-4486-bb90-9622743bba46.png)

**Comment by RiX012** [comment]
> Ik was benieuwd (ter lering en vermaak) welke alternatieven er waren en hoe het huidige voorstel tot stand is gekomen?

Ah ok. Nu snap ik hem. Hier is geen heel uitgebreide analyse voor gedaan. Het model waar `eis` direct aan `onderwerp` zit gaf niet afdoende flexibiliteit om met verificaties om te gaan. Het ultieme expliciet modelleren kan uiteraard met het 'role based modelling'. Deze specificatie heeft echter tot doel om zo minimalistisch/makkelijk mogelijk te zijn. Vandaar dat toen geconstateerd werd dat de standaard NEN2660-2 oplossing niet voldeed er een zo minimaal mogelijke uitbreiding is gedaan.
