### ISSUE TITLE
Concept opnemen bij status eis

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#65]
Aanvullen picklist bij eisstatus met concept, ooki in informatiemodel

**Comment by ElisabethKloren** [comment]
ik ben zo vrij geweest de documewntatie al aan te passen:

<dt><dfn>Vervallen
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Concept">csw:Concept</a>

**Comment by RiX012** [comment]
Ok done
