### ISSUE TITLE
Metadata toevoegen aan CSV 

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#67]
Volgens [deze handleiding](https://csvw.org/guides/how-to-make-csvw.html) kun je metadata toevoegen aan je csv file zodat deze getransformeerd kan worden naar json
De vraag is of we dit ook willen toepassen in de contractspecificaties

**Comment by ElisabethKloren** [comment]
wordt hier gebruik gemaakt van https://www.w3.org/TR/2015/REC-tabular-metadata-20151217

**Comment by ElisabethKloren** [comment]
@RiX012 wat raadt jij aan, zouden we een vaste set metadata kunnen maken die gebruikt kunnen worden in elk project, of moet er  dan een contract-specifieke metadata worden toegevoegd?

**Comment by RiX012** [comment]
> Volgens [deze handleiding](https://csvw.org/guides/how-to-make-csvw.html) kun je metadata toevoegen aan je csv file zodat deze getransformeerd kan worden naar json
> De vraag is of we dit ook willen toepassen in de contractspecificatie

Eerste overweging zou moeten zijn of we dit al in de initiële release willen stoppen. Ondanks dat het vele voordelen biedt is de basis van het werk dat het zo simpel mogelijk toepasbaar moet zijn, dus wellicht dat dit dan de zaken compliceert? 
Dus overweging: opnemen in de todo sectie of toch implementeren. 

Indien het laatste :
> wordt hier gebruik gemaakt van https://www.w3.org/TR/2015/REC-tabular-metadata-20151217

Ja, maar CSVW omvat dus meer. De simpelste vorm van dit toepassen is zorgen dat in de JSON file die bij de CSV hoort expliciet aangeven wordt wat de taalbinding naar de Constractspecificaties ontology is. Maar het is dus ook voor een deel redundant omdat we dat dus eigenlijk met deze specificatie doen :)

**Comment by ElisabethKloren** [comment]
Ok, dus het zou gaan om deze specificaties: https://csvw.org/standards.html

De oplossing is niet redundant; de Respec is meer voor de menselijke lezer, de metadata is voor de computer. 

En voor de complexiteit van de oplossing blijft mijn vraag aan @RiX012 openstaan: is het een standaard set metadata, of moet iedere opsteller van een contracteisendataset zelf ook in json metadata toevoegen?

**Comment by RiX012** [comment]
> En voor de complexiteit van de oplossing blijft mijn vraag aan @RiX012 openstaan: is het een standaard set metadata, of moet iedere opsteller van een contracteisendataset zelf ook in json metadata toevoegen?

Ik weet niet of ik helemaal begrijp wat je bedoelt. Maar in de JSON file staat niet persé metadata. In de file zou dan staan wat de taalbinding is. Dus in de JSON file zou staan dat de kolom EisNaam, correspondeert met skos:prefLabel en dat het datatype xsd:string zou zijn. 

De JSON file zou dan ook dus door onze standaard manier van taalbinding eigenlijk steeds voor 90% gelijk zijn.

**Comment by ElisabethKloren** [comment]
dus 10% moet worden aangepast - hoe ingewikkeld is dat? Kan een handige ingenieur dit zelf schrijven/automatiseren bij uitdraaien van een dataset uit een applicatie? 

Als het alleen een kwestie is van "vul hier je projectnaam, datum en plaats in" ofzo, dan is het wel tof in deze release. ALS jij of Redmer hier tijd voor hebben en het in een paar uurtjes opgesteld kan worden zie ik wel meerwaarde

**Comment by RiX012** [comment]
Goed, ik ga het proberen

**Comment by RiX012** [comment]
Eerste versie gewoon gecommit als hfst 6

**Comment by RiX012** [comment]
Nu opgenomen in ReSpec en voorbeeldbestanden
