### ISSUE TITLE
maximum aantal tekens in informatiemodel opnemen

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#69]
In verband met regels in de veelgebruikte applicaite relatics worden maimum aantal tekens voorgeschreven - kan ik dit ook in het informatiemodel opnemen, hoe doe ik dat in de LACES Library Manager?

**Comment by RiX012** [comment]
Dit vind ik niet thuishoren in een specificatie. Deze dient software onafhankelijk te zijn. Het is te zien als een limitatie van Relatics (of eigenlijk dus SQL database) dat dit niet kan. 

Als je er toch iets over zou willen opnemen zou ik het alleen als ADVISEMENT of WARNING opnemen in de tekst.

**Comment by ElisabethKloren** [comment]
Akkoord, ik zal hier een tekst over opnemen in de inleiding
