### ISSUE TITLE
Meerdere altlabels gebruiken

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#70]
eisTitel, onderwerpNaam, documentNaam zijn allemaal attribute naa/preflabel in het informatiemodel

Kan ik beter drie altlabels maken, of toch drie verschillende attributes?

**Comment by RiX012** [comment]
Beter drie altLabels, de mapping is namelijk afhankelijk van waar het attribuut wordt gebruikt.

**Comment by ElisabethKloren** [comment]
Ik heb het gecheckt; in de tekst stond nog dat het verificatiemoment een skos:note is, maar er is ook een apart concept cs:verificationMoment; ik heb dit in de tekst aangepast, omdat er anders twee "notes" worden toegevoegd aan het verificatievoorschrift (0:1)
