### ISSUE TITLE
Informatieproduct: is dat een Document?

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#71]
Informatieproduct: is dat een Document? In dat geval moet een document ook een definitie kunnen krijgen
Of we moeten informatieproduct nog toevoegen als concept

**Comment by RiX012** [comment]
Ja het is mijns inziens een document, mocht er een specifieke definitie nodig zijn dan is het een subklasse van Document.

**Comment by ElisabethKloren** [comment]
Ik heb het attribut "definitie" (skos:definition) toegevoegd als attribuut van een document, in de uitwisseling per tabel van alleen een informatielevering een definitie krijgen, de andere documenten worden zonder definitie overgedragen.
