### ISSUE TITLE
dct:references én "see also"

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/contractspecificaties#72]
In de library manager heeft een eis een attribuut "referentieDocument" (dct:references)
Een eis heeft ook een relatie "see also" met verwijzing naar een document

Is dit dubbel, of snap ik het gewoon niet en is dit nodig om het attribuut beter te kunnen duiden?

**Comment by RiX012** [comment]
Klopt, ik heb het attribuut verwijderd en de seeAlso aangepast naar references. Hiermee is het dus eenduidig en wordt een relatie gebruikt ipv een attribuut.
